# Welcome to Jekyll!
#
# Site settings
# in the templates via {{ site.myvariable }}.
title: Microsoft Open Source
email:
description: |

twitter_username: openatmicrosoft
github_username: microsoft

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

collections:
  projects:
    output: false
  posts:
    output: false
  community:
    output: false

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - script
  - vendor/gems
  - node_modules
  - node_modules/**/CHANGELOG.md
  - CHANGELOG.md
  - gulpfile.js
  - package.json
  - package-lock.json
seo:

twitter:
  username: openatmicrosoft

defaults:
  -
    scope:
      path: ""
    values:
      image: assets/images/social-card.png
      layout: default
