name: Build the content
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #       actions/checkout@v2
    - uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf
    - name: debug-startup
      run: pwd && whoami
    #       azure/docker-login@v1
    - uses: azure/docker-login@210cfedcb2e18efca1a159af35649e6f3b092f22
      with:
        login-server: 'docker.pkg.github.com'
        username: ${{ secrets.READONLY_PACKAGE_SP }}
        password: ${{ secrets.READONLY_PACKAGE_TOKEN }}
    - name: jekyll-build
      run: |
        docker run -i -v ${PWD}:/usr/local/site docker.pkg.github.com/microsoft/opensource.microsoft.com/custom-jekyll-builder:latest sh << COMMANDS
        pwd && whoami
        cd /usr/local/site
        ls -la
        bundle install
        npm i
        ./node_modules/gulp/bin/gulp.js build
        JEKYLL_ENV=opensource.microsoft.com jekyll build
        COMMANDS
    - name: compress-site
      run: tar -czvf ../site.tar.gz .
      working-directory: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/_site
    #       actions/upload-artifact/v2
    - uses: actions/upload-artifact@58740802ef971a2d71eff71e63d48ab68d1f5507
      with:
        name: website
        path: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/site.tar.gz