name: Build the content
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: debug-startup
      run: pwd && whoami
    - uses: azure/docker-login@v1
      with:
        login-server: 'docker.pkg.github.com'
        username: ${{ secrets.READONLY_PACKAGE_SP }}
        password: ${{ secrets.READONLY_PACKAGE_TOKEN }}
    - name: jekyll-build
      run: |
        docker run -i -v ${PWD}:/usr/local/site docker.pkg.github.com/microsoft/opensource.microsoft.com/custom-jekyll-builder:latest sh << COMMANDS
        pwd && whoami
        cd /usr/local/site
        ls -la
        bundle install
        npm i
        ./node_modules/gulp/bin/gulp.js build
        JEKYLL_ENV=opensource.microsoft.com jekyll build
        COMMANDS
    - name: compress-site
      run: tar -czvf ../site.tar.gz .
      working-directory: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/_site
    - uses: actions/upload-artifact@v2
      with:
        name: website
        path: /home/runner/work/opensource.microsoft.com/opensource.microsoft.com/site.tar.gz