name: Build the builder
on:
  push:
    branches:
      - main
    paths:
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'package.json'
      - 'package-lock.json'
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile.builder
        tags: latest
        tag_with_sha: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: microsoft/opensource.microsoft.com/custom-jekyll-builder